version: '2'
services:
  base:
    build: .
    image: ropelive/home

  server:
    extends: base
    command: gulp watch-server
    environment:
      - "MONGO_ADDR=mongodb://mongo:27017/rope"
      - "WEB_URL=http://localhost:9001"
    ports:
      - "9000:9000"
    links:
      - mongo
    volumes:
      - ./app:/opt/rope/app
      - ./server:/opt/rope/server
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0.15
    ports:
      - "27017:27017"
    volumes:
      - /data/db
